data = [
    {'name': 'Instagram', 'follower_count': 685.7, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 648.3, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 504.9, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 422.3, 'description': 'Musician and actress',
     'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 400.3, 'description': 'Reality TV star and businesswoman',
     'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 397.0, 'description': 'Actor and professional wrestler',
     'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 380.4, 'description': 'Musician and actress',
     'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 364.1, 'description': 'Reality TV star and businesswoman',
     'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 320.0, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 311.0, 'description': 'Reality TV star', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 306.8, 'description': 'Sportswear brand', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 294.8, 'description': 'Model and reality TV star',
     'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 293.1, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'National Geographic', 'follower_count': 284.3, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 281.0, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 266.4, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 253.7, 'description': 'Musician and actress',
     'country': 'United States'},
    {'name': 'Barbie', 'follower_count': 229.4, 'description': 'Fashion doll brand', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 222.5, 'description': 'Reality TV star',
     'country': 'United States'},
    {'name': 'Neymar Jr', 'follower_count': 219.4, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Miley Cyrus', 'follower_count': 216.9, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 206.9, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 184.8, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 169.3, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159.8, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 157.4, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Real Madrid C.F.', 'follower_count': 155.9, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Rihanna', 'follower_count': 152.0, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 150.0, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 148.0, 'description': 'Comedian and TV host',
     'country': 'United States'},
    {'name': 'FC Barcelona', 'follower_count': 146.0, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Billie Eilish', 'follower_count': 144.0, 'description': 'Musician', 'country': 'United States'},
    {'name': 'UEFA Champions League', 'follower_count': 142.0, 'description': 'Football competition',
     'country': 'Europe'},
    {'name': 'NASA', 'follower_count': 140.0, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 138.0, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Drake', 'follower_count': 136.0, 'description': 'Rapper', 'country': 'Canada'},
    {'name': "Victoria's Secret", 'follower_count': 134.0, 'description': 'Lingerie brand',
     'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 132.0, 'description': 'Actor', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 130.0, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'Shraddha Kapoor', 'follower_count': 128.0, 'description': 'Actress', 'country': 'India'},
    {'name': 'Snoop Dogg', 'follower_count': 126.0, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Shawn Mendes', 'follower_count': 124.0, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Gigi Hadid', 'follower_count': 122.0, 'description': 'Model', 'country': 'United States'},
    {'name': 'Priyanka Chopra', 'follower_count': 120.0, 'description': 'Actress and singer', 'country': 'India'},
    {'name': 'Chris Hemsworth', 'follower_count': 118.0, 'description': 'Actor', 'country': 'Austrailia'}]


